function y = dr_ht(mdr,hss,approx,x)
%This function evaluates decision rules for state variables of a DSGE
%model solved with the algorithm by Levintal (2017).
%The order of approximation can go from 2 up to 5.
%Inputs are:
%mdr: struct with derivatives of decision rules, generated by the algorithm.
%gss: nx-by-1 vector of deterministic steady-state for states.
%approx: order of approximation
%x: nx-by-N vector of state variables, where N>=1, and each column is a particular
%realization of states.
%
%The output is a nx-by-N matrix, where each column represents time t+1
%state variables (excluding future innovations), under a particular
%realization of today's states.
%
% Copyright (C) 2024 Guillermo Hausmann Guil

[~,s2] = size(x);

x = [x;ones(1,s2)];
hx = mdr.hx;
hx2 = mdr.hxx;
kx2 = mykron1(x,x);
if approx>2
    hx3 = mdr.hxxx;
    kx3 = mykron1(kx2,x);
end
if approx>3
    hx4 = mdr.hxxxx;
    kx4 = mykron1(kx3,x);
end
if approx>4
    hx5 = mdr.hxxxxx;
    kx5 = mykron1(kx4,x);
end

if approx==2
    y = hss +  hx*x + 0.5*hx2*kx2;
end
if approx==3
    y = hss +  hx*x + 0.5*hx2*kx2 + (1/6)*hx3*kx3;
end
if approx==4
    y = hss +  hx*x + 0.5*hx2*kx2 + (1/6)*hx3*kx3 + (1/24)*hx4*kx4;
end
if approx==5
    y = hss +  hx*x + 0.5*hx2*kx2 + (1/6)*hx3*kx3 + (1/24)*hx4*kx4 + (1/120)*hx5*kx5;
end

