function y = compute_betta_soe_uzawa_dynare(b1,M_,options_,oo_,eps_ind,guess)
%This function calibrates the value pssi2_star (and hence of the discount
%factor at the model of interest) consistent with a target SSS of bonds,
%with Uzawa as the auxiliary model.
%Inputs are the target SSS level of bonds, struct files generated by Dynare
%(M_, options_, and oo_), the index of the epsilon variable in the vector
%yt of endogenous variables, and a initial guess.
%Output is pssi2_star.
%
% Copyright (C) 2024 Guillermo Hausmann Guil

options_.order=2; %Choose a second-order solution
options_.k_order_solver=0;

%Call fsolve to find a candidate psi2 that zeroes the residual calibration
%function:
my_evalf= @(x)calib_sss_soe_uzawa_dynare(x,b1,M_,options_,oo_,eps_ind);

y = fsolve(my_evalf,guess,optimset('TolFun',1e-15,'Display','off'));
